apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ngx-instance-0-dep
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ngx-instance-0-dep
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: bigchaindb/nginx_http:unstable
        imagePullPolicy: Always
        env:
        - name: CLUSTER_FRONTEND_PORT
          valueFrom:
            configMapKeyRef:
              name: vars
              key: cluster-frontend-port
        - name: HEALTH_CHECK_PORT
          valueFrom:
            configMapKeyRef:
              name: vars
              key: cluster-health-check-port
        - name: DNS_SERVER
          valueFrom:
            configMapKeyRef:
              name: vars
              key: cluster-dns-server-ip
        - name: MONGODB_BACKEND_HOST
          valueFrom:
            configMapKeyRef:
              name: vars
              key: ngx-mdb-instance-name
        - name: MONGODB_BACKEND_PORT
          valueFrom:
            configMapKeyRef:
              name: vars
              key: mongodb-backend-port
        - name: BIGCHAINDB_BACKEND_HOST
          valueFrom:
            configMapKeyRef:
              name: vars
              key: ngx-bdb-instance-name
        - name: BIGCHAINDB_API_PORT
          valueFrom:
            configMapKeyRef:
              name: vars
              key: bigchaindb-api-port
        - name: BIGCHAINDB_WS_PORT
          valueFrom:
            configMapKeyRef:
              name: vars
              key: bigchaindb-ws-port
        - name: TM_PUB_KEY_ACCESS_PORT
          valueFrom:
            configMapKeyRef:
              name: tendermint-config
              key: tm-pub-key-access
        - name: TM_BACKEND_HOST
          valueFrom:
            configMapKeyRef:
              name: tendermint-config
              key: ngx-tm-instance-name
        - name: TM_P2P_PORT
          valueFrom:
            configMapKeyRef:
              name: tendermint-config
              key: tm-p2p-port
        ports:
        - containerPort: "<cluster-health-check-port from ConfigMap>"
          protocol: TCP
          name: ngx-health
        - containerPort: "<cluster-frontend-port from ConfigMap>"
          protocol: TCP
        - containerPort: "<tm-pub-key-access from ConfigMap>"
          protocol: TCP
          name: tm-pub-key
        - containerPort: "<tm-p2p-port from ConfigMap>"
          protocol: TCP
          name: tm-p2p-port
        livenessProbe:
          httpGet:
            path: /health
            port: ngx-health
          initialDelaySeconds: 15
          periodSeconds: 15
          failureThreshold: 3
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 200m
            memory: 768Mi
      restartPolicy: Always
