# Copyright BigchainDB GmbH and BigchainDB contributors
# SPDX-License-Identifier: (Apache-2.0 AND CC-BY-4.0)
# Code is Apache-2.0 and docs are CC-BY-4.0

repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v1.1.1
    hooks:
    -   id: trailing-whitespace
        args: ['--no-markdown-linebreak-ext']
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: check-added-large-files
    -   id: flake8

-   repo: git://github.com/chewse/pre-commit-mirrors-pydocstyle
    sha: v2.1.1
    hooks:
    -   id: pydocstyle
        # list of error codes to check, see: http://www.pydocstyle.org/en/latest/error_codes.html
        args: ['--select=D204,D201,D209,D210,D212,D300,D403']

# negate the exclude to only apply the hooks to 'bigchaindb' and 'tests' folder
exclude: '^(?!bigchaindb/)(?!tests/)(?!acceptance/)'
