sudo: required
language: python
cache: pip
python:
  - 3.4
  - 3.5

before_install:
  - source /etc/lsb-release
  - echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee -a /etc/apt/sources.list.d/rethinkdb.list
  - wget -qO- https://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
  - sudo apt-get update -qq

install:
  - sudo apt-get install rethinkdb
  - pip install -e .[test]
  - pip install codecov

before_script: rethinkdb --daemon

script: py.test -n auto -s -v --cov=bigchaindb

after_success: codecov
