language: python
cache: pip

env:
  - TOXENV=py34-mdb
  - TOXENV=py34-rdb
  - TOXENV=py35-mdb
  - TOXENV=py35-rdb
  - TOXENV=flake8
  - TOXENV=docsroot
  - TOXENV=docsserver

before_install: sudo .ci/travis-before-install.sh

install: .ci/travis-install.sh

before_script: .ci/travis-before-script.sh

script: tox -e ${TOXENV}

after_success: .ci/travis-after-success.sh
