sudo: required

dist: trusty

services:
  - docker

language: python
cache: pip

python:
  - 3.5
  - 3.6
  
env:
  - TOXENV=flake8
  - TOXENV=docsroot
  - TOXENV=docsserver

matrix:
  fast_finish: true
  exclude:
  - python: 3.5
    env: TOXENV=flake8 
  - python: 3.5 
    env: TOXENV=docsroot
  - python: 3.5 
    env: TOXENV=docsserver
  include:
  - python: 3.5
    env: BIGCHAINDB_DATABASE_BACKEND=rethinkdb
  - python: 3.5
    env:
    - BIGCHAINDB_DATABASE_BACKEND=mongodb
    - BIGCHAINDB_DATABASE_SSL=
  - python: 3.6
    env: BIGCHAINDB_DATABASE_BACKEND=rethinkdb
  - python: 3.6
    env:
    - BIGCHAINDB_DATABASE_BACKEND=mongodb
    - BIGCHAINDB_DATABASE_SSL=
  - python: 3.5
    env:
    - BIGCHAINDB_DATABASE_BACKEND=mongodb
    - BIGCHAINDB_DATABASE_SSL=true
  - python: 3.6
    env:
    - BIGCHAINDB_DATABASE_BACKEND=mongodb
    - BIGCHAINDB_DATABASE_SSL=true

before_install: sudo .ci/travis-before-install.sh

install: .ci/travis-install.sh

before_script: .ci/travis-before-script.sh

script: .ci/travis_script.sh

after_success: .ci/travis-after-success.sh
