version: '3'

services:
  bdocs:
    build:
      context: .
      dockerfile: ./Dockerfile-dev
    volumes:
      - .:/usr/src/app/
    command: make -C docs/server html
  vdocs:
    image: nginx
    ports:
      - '33333:80'
    volumes:
      - ./docs/server/build/html:/usr/share/nginx/html
