apiVersion: v1
kind: Service
metadata:
  name: ngx-https-instance-0
  namespace: default
  labels:
    name: ngx-https-instance-0
  annotations:
    # NOTE: the following annotation is a beta feature and
    # only available in GCE/GKE and Azure as of now
    service.beta.kubernetes.io/external-traffic: OnlyLocal
spec:
  selector:
    app: ngx-https-instance-0-dep
  ports:
  - port: "<cluster-frontend-port from ConfigMap>"
    targetPort: "<cluster-frontend-port from ConfigMap>"
    name: public-secure-cluster-port
    protocol: TCP
  - port: 80
    targetPort: 80
    name: public-insecure-cluster-port
    protocol: TCP
  - port: "<mongodb-frontend-port from ConfigMap>"
    targetPort: "<mongodb-frontend-port from ConfigMap>"
    name: public-mdb-port
    protocol: TCP
  - port: "<threescale-api-port from ConfigMap>"
    targetPort: "<threescale-api-port from ConfigMap>"
    name: public-threescale-port
    protocol: TCP
  type: LoadBalancer
