# Copyright Â© 2020 Interplanetary Database Association e.V.,
# BigchainDB and IPDB software contributors.
# SPDX-License-Identifier: (Apache-2.0 AND CC-BY-4.0)
# Code is Apache-2.0 and docs are CC-BY-4.0

apiVersion: v1
kind: Service
metadata:
  # Name of mongodb instance you are trying to connect to
  # e.g. mdb-instance-0
  name: "<remote-mongodb-host>"
  namespace: default
spec:
  ports:
  - port: "<mongodb-backend-port from ConfigMap>"
  type: ExternalName
  # FQDN of remote cluster/NGINX instance
  externalName: "<dns-name-remote-nginx>"