apiVersion: v1
kind: Service
metadata:
  name: bdb-instance-0
  namespace: default
  labels:
    name: bdb-instance-0
spec:
  selector:
    app: bdb-instance-0-dep
  ports:
  - port: "<bigchaindb-api-port from ConfigMap>"
    targetPort: "<bigchaindb-api-port from ConfigMap>"
    name: bdb-api-port
    protocol: TCP
  - port: "<bigchaindb-ws-port from ConfigMap>"
    targetPort: "<bigchaindb-ws-port from ConfigMap>"
    name: bdb-ws-port
    protocol: TCP
  - port: "<tm-abci-port from ConfigMap>"
    targetPort: "<tm-abci-port from ConfigMap>"
    name: tm-abci-port
    protocol: TCP
  type: ClusterIP
  clusterIP: None
