---
# This playbook deploys a BigchainDB node in one machine (one-m).

- name: Ensure a one-machine BigchainDB node is configured properly
  hosts: all
  remote_user: ubuntu

  roles:
    - bcdb_base
    - ntp
    - db_storage
    - install_rethinkdb
