##################################################
# This config file runs mongo:3.4.1 as a service #
##################################################

apiVersion: v1
kind: Service
metadata:
  name: mdb-service
  namespace: default
  labels:
    name: mdb-service
spec:
  selector:
    app: mdb
  ports:
  - port: 27017
    targetPort: 27017
    name: mongodb-api
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: StatefulSet 
metadata:
  name: mdb
  namespace: default
spec:
  serviceName: mdb
  replicas: 1
  template:
    metadata:
      name: mdb
      labels:
        app: mdb
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongodb
        image: mongo:3.4.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
          hostPort: 27017
          name: mdb-port
          protocol: TCP 
        volumeMounts:
        - name: mdb-data
          mountPath: /data
        resources:
          limits:
            cpu: 200m
            memory: 768Mi
        livenessProbe:
          tcpSocket:
            port: mongo-port
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 15
          timeoutSeconds: 1
      restartPolicy: Always
      volumes:
      - name: mdb-data
        hostPath:
          path: /disk/mdb-data
