---
- name: Add MongoDB Repo | CentOS
  yum_repository:
    name: "{{ mongodb_package }}"
    gpgcheck: yes
    gpgkey: https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc
    baseurl: "{{ mongodb_yum_base_url }}"
    file: "{{ mongodb_package }}"
    description: "MongoDB Repo"
    enabled: yes
  tags: [mongodb]

- name: Install MongoDB | CentOS
  yum:
    name: "{{ mongodb_package }}"
    state: present
    update_cache: yes
  tags: [mongodb]