---
- name: Add MongoDB Repo | Fedora
  yum_repository:
    name: "{{ mongodb_package }}"
    gpgcheck: yes
    gpgkey: https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc
    baseurl: "{{ mongodb_dnf_base_url }}"
    file: "{{ mongodb_package }}"
    description: "MongoDB Repo"
    enabled: yes
  tags: [mongodb]

- name: Install MongoDB | Fedora
  dnf:
    name: "{{ mongodb_package }}"
    state: present
  tags: [mongodb]