# Copyright BigchainDB GmbH and BigchainDB contributors
# SPDX-License-Identifier: (Apache-2.0 AND CC-BY-4.0)
# Code is Apache-2.0 and docs are CC-BY-4.0

---
- name: Check if Docker is running
  command: docker info
  register: info_result
  ignore_errors: True
  when: stack_type|lower == "docker" or stack_type|lower == "cloud"
  tags: [bigchaindb]

- name: Error! Docker not running
  fail:
    msg: "Docker not running."
  when: (stack_type|lower == "docker" or stack_type|lower == "cloud") and info_result is failed
  tags: [bigchaindb]

- import_tasks: start.yml
  when: action|lower == 'start'
  tags: [bigchaindb]

- import_tasks: stop.yml
  when: action|lower == 'stop'
  tags: [bigchaindb]