## Note: data values do NOT have to be base64-encoded in this file. 

## vars is common environment variables for this BigchaindB node
apiVersion: v1
kind: ConfigMap
metadata:
  name: vars
  namespace: default
data:
  # MongoDB
  mdb-instance-name: "<name of the mdb instance>"
  # BigchainDB
  bdb-instance-name: "<name of the bdb instance>"
  # NGINX
  ngx-instance-name: "<name of the ngx instance>"
  # MongoDB Monitoring Agent
  mdb-mon-instance-name: "<name of the mdb monitoring agent instance>"
  # MongoDB Backup Agent
  mdb-bak-instance-name: "<name of the mdb backup agent instance>"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bdb-config
  namespace: default
data:
  # Colon-separated list of all *other* nodes' BigchainDB public keys.
  bdb-keyring: "<':' separated list of public keys>"
  # BigchainDB instance authentication user name
  bdb-user: "<user name>"
  # BigchainDB public key of *this* node.
  # Example: "EPQk5i5yYpoUwGVM8VKZRjM8CYxB6j8Lu8i8SG7kGGce"
  bdb-public-key: "<public key>"
