---
dependencies_deb:
  - g++
  - python3-dev
  - libffi-dev
  - build-essential
  - libssl-dev
  - python3-pip

dependencies_yum:
  - gcc-c++
  - "@Development Tools"
  - python35u-devel
  - libffi-devel
  - openssl-devel
  - python35u-setuptools

dependencies_dnf:
  - gcc-c++
  - redhat-rpm-config
  - "@Development Tools"
  - python3-devel
  - libffi-devel
  - openssl-devel
  - python3-pip

python_pip_upgrade: true
python_setuptools_upgrade: true

# Host configuration
distribution_name: "{{ ansible_distribution|lower }}"
distribution_codename: "{{ ansible_distribution_release|lower }}"
distribution_major: "{{ ansible_distribution_major_version }}"

directories:
  - /data

backend_db: mongodb #[mongodb]
bigchaindb_config_path: /data/.bigchaindb

bigchaindb_server_bind: "0.0.0.0:9984"
bigchaindb_log_file: "{{ ansible_env.HOME }}/bigchaindb.log"

# Docker configuration
bigchaindb_image_name: "bigchaindb/bigchaindb"
bigchaindb_docker_name: "bigchaindb"
bigchaindb_default_port: 9984
bigchandb_host_port: 59984
bigchaindb_host_mount_dir: "{{ ansible_env.HOME }}/bigchaindb_docker"
bdb_docker_net_name: "bdb_network"
